version: "3.8"

services:
  fastapi:
    hostname: fastapi
    container_name: fastapi
    environment:
      UVICORN_LOG_LEVEL: info
      UVICORN_PORT: 8080
    build:
      context: fastapi
    ports:
      - "8080:8080"